name: matjazv Blog
description: >
    Matjaz Verbole Techical Blog
about: >
    Writings about techical stuff.

master_repo: false
url: "http://matjazv.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 10

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Matjaz Verbole
  avatar:         "https://avatars1.githubusercontent.com/u/676797?s=460&v=4"
  email:          "verbole@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  #twitter: vinitkme
  github: https://github.com/matjazv
  #stackexchange: https://stackoverflow.com/users/859112/vinit-kumar?tab=profile
  linkedin: https://www.linkedin.com/in/matjaz-verbole
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
